// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkav_BbVY-PAhfOyhOWuym_zEq1cDikrM',
    appId: '1:639290006086:web:1ffb61530dd3fbd7d58847',
    messagingSenderId: '639290006086',
    projectId: 'sayeret-people',
    authDomain: 'sayeret-people.firebaseapp.com',
    storageBucket: 'sayeret-people.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1iIY7Hs9ayVzAaR3k744JFAsyp6AIpbI',
    appId: '1:639290006086:android:a815c1984c548d2ed58847',
    messagingSenderId: '639290006086',
    projectId: 'sayeret-people',
    storageBucket: 'sayeret-people.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn-1Db0BViClUWhSPgMHFNdHA-NmQvm0M',
    appId: '1:639290006086:ios:6533f7299ae50ebcd58847',
    messagingSenderId: '639290006086',
    projectId: 'sayeret-people',
    storageBucket: 'sayeret-people.appspot.com',
    iosClientId: '639290006086-tm0pe4deklsh658q0n5c7mtqrjm7dc42.apps.googleusercontent.com',
    iosBundleId: 'com.biton.sayeretpeople.sayeretPeople',
  );
}
